// /concepts/hallucination/ — SEO pillar for "llm hallucination",
// "ai hallucination", "what is ai hallucination", "stop llm hallucination".

import type { Metadata } from "next";
import { breadcrumbListSchema } from "@/lib/methodology-version";

const PUBLISHED = "2026-05-16";
const TITLE = "LLM hallucination — what it is, why it happens, what reduces it";
const SUBTITLE =
  "Hallucination is the LLM-era word for confidently asserting facts that aren't real. It has measurable rates, predictable causes, and a layered set of mitigations. Here's the full picture.";
const SLUG = "hallucination";
const CANONICAL = `https://sourcescore.org/concepts/${SLUG}/`;

export const metadata: Metadata = {
  title: { absolute: TITLE },
  description: SUBTITLE,
  alternates: { canonical: CANONICAL },
  openGraph: {
    title: TITLE,
    description: SUBTITLE,
    url: CANONICAL,
    type: "article",
    publishedTime: PUBLISHED,
  },
  twitter: { card: "summary_large_image", title: TITLE, description: SUBTITLE },
};

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "TechArticle",
  headline: TITLE,
  description: SUBTITLE,
  datePublished: PUBLISHED,
  dateModified: PUBLISHED,
  mainEntityOfPage: CANONICAL,
  author: {
    "@type": "Organization",
    "@id": "https://sourcescore.org/#organization",
    name: "SourceScore",
    url: "https://sourcescore.org",
  },
  publisher: {
    "@type": "Organization",
    "@id": "https://sourcescore.org/#organization",
    name: "SourceScore",
    logo: { "@type": "ImageObject", url: "https://sourcescore.org/logo.svg" },
  },
  about: [
    { "@type": "Thing", name: "LLM hallucination" },
    { "@type": "Thing", name: "Factual error" },
    { "@type": "Thing", name: "Citation verification" },
  ],
};

const definedTermSchema = {
  "@context": "https://schema.org",
  "@type": "DefinedTerm",
  name: "LLM hallucination",
  description:
    "A factual error generated by a large language model — typically presented with the same fluency and confidence as a correct statement. Includes invented facts, misattributed quotes, fabricated citations, and stitched-together claims that combine real fragments incorrectly.",
  inDefinedTermSet: "https://sourcescore.org/concepts/",
  url: CANONICAL,
};

export default function HallucinationConcept() {
  return (
    <article className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-14">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(definedTermSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            breadcrumbListSchema([
              { name: "SourceScore", url: "https://sourcescore.org/" },
              { name: "Concepts", url: "https://sourcescore.org/concepts/" },
              { name: "Hallucination", url: CANONICAL },
            ]),
          ),
        }}
      />

      <nav className="text-sm text-zinc-500 mb-6">
        <a href="/" className="hover:underline">SourceScore</a>
        <span className="mx-2">›</span>
        <a href="/concepts/" className="hover:underline">Concepts</a>
        <span className="mx-2">›</span>
        <span className="text-zinc-700 dark:text-zinc-300">Hallucination</span>
      </nav>

      <header className="mb-10">
        <p className="text-xs uppercase tracking-wide text-zinc-500 mb-2">
          Concept · {PUBLISHED}
        </p>
        <h1 className="text-3xl sm:text-4xl font-semibold leading-tight mb-3">
          {TITLE}
        </h1>
        <p className="text-zinc-600 dark:text-zinc-400 text-lg leading-relaxed">
          {SUBTITLE}
        </p>
      </header>

      <section className="prose prose-zinc dark:prose-invert max-w-none">
        <h2 id="definition">Definition</h2>
        <p>
          <strong>Hallucination</strong> in the LLM context is a factual
          error generated by a large language model, typically presented
          with the same fluency and confidence as a correct statement.
          The model produces text that <em>looks</em> right — proper
          grammar, plausible structure, real-sounding citations — but
          contains assertions that don&apos;t correspond to verifiable
          reality.
        </p>
        <p>
          The word is borrowed from psychiatry but the mechanism is
          different. LLMs aren&apos;t having sensory experiences. They&apos;re
          producing plausible next tokens. When the most plausible
          continuation happens to be false, you get a hallucination.
        </p>

        <h2 id="taxonomy">Five categories of hallucination</h2>
        <ol>
          <li>
            <strong>Fabricated facts.</strong> The model invents a fact
            that doesn&apos;t exist. &quot;The library libfoo 3.4 introduced
            the bar() function&quot; — when libfoo never had a bar() function.
          </li>
          <li>
            <strong>Misattributed quotes.</strong> Real quote, wrong
            person. &quot;As Einstein said: be the change you want to see
            in the world&quot; — which Einstein never said.
          </li>
          <li>
            <strong>Fabricated citations.</strong> The model produces a
            URL, paper, or book that doesn&apos;t exist. Especially common
            with academic citation tasks.
          </li>
          <li>
            <strong>Stitched-together claims.</strong> Real fragments
            recombined incorrectly. &quot;GPT-4 was released by Anthropic
            in 2023&quot; — GPT-4 is real, 2023 is real, but Anthropic
            isn&apos;t the publisher.
          </li>
          <li>
            <strong>Temporal hallucination.</strong> Facts true at training
            time, presented as currently true. &quot;The latest version of
            Python is 3.11&quot; — true when the model was trained, no
            longer true now.
          </li>
        </ol>

        <h2 id="rates">Measured rates (2026 data)</h2>
        <p>
          Hallucination rate depends heavily on domain, model, and
          prompt. Published research on frontier models in 2026
          generally shows:
        </p>
        <ul>
          <li>
            <strong>~1-5% on well-trodden questions.</strong> Capitals of
            countries, basic biology, common math. The training set
            covered these heavily; the model has redundant evidence.
          </li>
          <li>
            <strong>~5-15% on moderately specialized queries.</strong>{" "}
            History of a tech company, mid-list scientist&apos;s
            publications, named software features. The training set has
            some coverage; the model interpolates.
          </li>
          <li>
            <strong>~15-40% on long-tail technical questions.</strong>{" "}
            Specific library version features, niche academic results,
            recent events past the training cutoff. The training set is
            thin or absent; the model fabricates plausibly.
          </li>
          <li>
            <strong>~30-60% on citation tasks.</strong> &quot;List 5
            papers that introduced technique X.&quot; The model is
            statistically rewarded for producing 5 entries even when
            fewer real ones exist, leading to invented citations.
          </li>
        </ul>
        <p>
          These rates have dropped roughly 2x year-over-year since 2022
          but haven&apos;t reached zero. They likely won&apos;t — the
          training objective (next-token plausibility) and the
          factuality objective (assertion correctness) aren&apos;t the
          same thing.
        </p>

        <h2 id="why-it-happens">Why hallucination happens</h2>
        <p>
          Six root causes, ordered by how addressable each is:
        </p>
        <ol>
          <li>
            <strong>Statistical sampling.</strong> The model generates
            the next token by sampling from a probability distribution.
            Sometimes the most-likely token is false. This is
            mathematically unavoidable in pure generation.
          </li>
          <li>
            <strong>Compression artifacts.</strong> A model with 70B
            parameters can&apos;t store every fact verbatim. Facts are
            compressed; compression is lossy. Edges blur.
          </li>
          <li>
            <strong>Training-set noise.</strong> The model trained on
            text that included wrong facts. It learned the wrong fact
            with the same fluency as the right one.
          </li>
          <li>
            <strong>Temporal cutoff.</strong> The model has no knowledge
            of events past its training cutoff but doesn&apos;t know it
            doesn&apos;t know. It fabricates.
          </li>
          <li>
            <strong>RLHF reward hacking.</strong> Models are fine-tuned
            with reinforcement learning to produce helpful responses.
            &quot;I don&apos;t know&quot; is often rated lower than a
            confident guess. The model learns to guess.
          </li>
          <li>
            <strong>Prompt ambiguity.</strong> The user asks a question
            with multiple correct interpretations; the model picks one;
            it doesn&apos;t match the user&apos;s intended scope.
          </li>
        </ol>

        <h2 id="mitigations">What reduces hallucination (ordered by impact)</h2>
        <ol>
          <li>
            <strong>Signed-claim verification</strong> (see{" "}
            <a href="/concepts/llm-grounding/">LLM grounding</a>).
            Post-process every assertion against a verified-claim
            catalog. Unverified assertions get flagged or stripped.
            Reduces hallucination from ~15-40% to &lt;1% on covered
            domains. Cost: per-call latency + catalog curation.
          </li>
          <li>
            <strong>Retrieval-augmented generation.</strong> Insert
            retrieved context into the prompt. Cuts hallucination
            roughly in half on covered domains. Cost: vector DB +
            retrieval latency.
          </li>
          <li>
            <strong>Confidence calibration.</strong> Train the model to
            say &quot;I don&apos;t know&quot; when uncertain. Helps but
            doesn&apos;t eliminate — the model has to know what it
            doesn&apos;t know, which is hard.
          </li>
          <li>
            <strong>Tool-call verification.</strong> Give the model a
            verify_claim() tool. Let it self-invoke when uncertain.
            Hybrid of (1) and human-in-the-loop.
          </li>
          <li>
            <strong>Prompt engineering for honesty.</strong>{" "}
            &quot;Answer only with information you can cite a specific
            source for.&quot; Modest impact; instruction-following on
            factuality is unreliable.
          </li>
          <li>
            <strong>Self-consistency sampling.</strong> Generate N
            answers, take the majority vote. Reduces variance but not
            bias — wrong-but-consistent answers stay wrong.
          </li>
          <li>
            <strong>Temperature = 0.</strong> Removes sampling
            randomness. Helps marginally; doesn&apos;t fix the
            underlying cause.
          </li>
        </ol>

        <h2 id="detection">Detecting hallucination at runtime</h2>
        <p>
          Three techniques for catching hallucination after generation
          but before display:
        </p>
        <ol>
          <li>
            <strong>Cite-or-strip.</strong> Require every assertion to
            have a citation. Strip uncited lines. This is the strongest
            pattern but requires curated claim catalog.
          </li>
          <li>
            <strong>Multi-model cross-check.</strong> Ask a second model
            &quot;is this true?&quot; about the first model&apos;s output.
            Crude but cheap. Catches obvious fabrications.
          </li>
          <li>
            <strong>External verification API.</strong> POST the claim to
            a service like{" "}
            <a href="/api/v1/verify"><code>/api/v1/verify</code></a>{" "}
            and check the response.{" "}
            <a href="/blog/verify-ai-facts-five-lines-python/">
              Five lines of Python
            </a>{" "}
            gets you a working version.
          </li>
        </ol>

        <h2 id="who-cares">Where hallucination cost is highest</h2>
        <ul>
          <li>
            <strong>Medical / legal / financial.</strong> User acts on
            wrong information; real-world harm. Mitigation: signed-claim
            verification + UX badges marking unverified assertions.
          </li>
          <li>
            <strong>Code generation.</strong> Model invents a function
            that doesn&apos;t exist; user&apos;s code crashes. Mitigation:
            type-aware retrieval over the actual library AST.
          </li>
          <li>
            <strong>Academic / research.</strong> Fabricated citations
            propagate. Mitigation: every cited source has a clickable
            URL that resolves.
          </li>
          <li>
            <strong>Customer support.</strong> Wrong product information
            costs trust. Mitigation: ground on the company&apos;s own
            documentation; don&apos;t answer out of scope.
          </li>
          <li>
            <strong>Public-facing chat.</strong> Wrong answer ends up
            in screenshots, social media. Mitigation: confidence
            thresholds; defer to humans when uncertain.
          </li>
        </ul>

        <h2 id="future">Will it ever be solved?</h2>
        <p>
          Probably not in the &quot;model never hallucinates&quot; sense.
          The training objective rewards plausibility, not truth, and
          plausible-but-false will always have non-zero probability.
        </p>
        <p>
          What will improve over time is the <em>infrastructure</em>{" "}
          around the model: better retrieval, better signed-claim
          catalogs, better verification APIs, better UX patterns for
          surfacing confidence. The model stays imperfect; the
          surrounding system makes the imperfection safe.
        </p>
        <p>
          The right mental model is not &quot;LLMs are calculators that
          sometimes give wrong answers.&quot; It&apos;s &quot;LLMs are
          fluent first-drafters that need a fact-checking pipeline
          downstream.&quot; The pipeline is the product.
        </p>

        <h2 id="references">Further reading</h2>
        <ul>
          <li>
            <a href="/concepts/llm-grounding/">LLM grounding</a> — the
            broader concept hallucination control falls under
          </li>
          <li>
            <a href="/blog/verify-ai-facts-five-lines-python/">
              Verifying AI-generated facts in 5 lines of Python
            </a>{" "}
            — hands-on hallucination filter
          </li>
          <li>
            <a href="/blog/why-no-performance-claims/">
              Why VERITAS doesn&apos;t ship performance-comparison claims
            </a>
          </li>
          <li>
            <a href="/quickstart/">Quickstart</a> — first API call in
            5 minutes
          </li>
          <li>
            <a href="/claims/">Browse the catalog</a> — 316 hand-verified
            AI/ML claims
          </li>
        </ul>
      </section>
    </article>
  );
}
