#!/usr/bin/env node
/**
 * Postbuild — generate sitemap.xml + sitemap-ai.xml from /out/.
 *
 * Walks the static export, picks every index.html, computes the URL,
 * writes both standard + AI-priority sitemaps to /out/.
 */
import { writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const OUT_DIR = "out";
const SITE = "https://sourcescore.org";
const TODAY = new Date().toISOString().slice(0, 10);

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const s = statSync(full);
    if (s.isDirectory()) walk(full, files);
    else if (entry === "index.html") files.push(full);
  }
  return files;
}

function urlFromPath(absPath) {
  const rel = relative(OUT_DIR, absPath).replace(/index\.html$/, "");
  if (rel === "") return `${SITE}/`;
  return `${SITE}/${rel}`;
}

const files = walk(OUT_DIR);
const urls = files.map(urlFromPath).sort();

// sitemap.xml — full set
const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap-0.9">',
  ...urls.map((u) => {
    const isHome = u === `${SITE}/`;
    const priority = isHome ? "1.0" : u.includes("/source/") ? "0.9" : "0.8";
    return `  <url><loc>${u}</loc><lastmod>${TODAY}</lastmod><changefreq>weekly</changefreq><priority>${priority}</priority></url>`;
  }),
  "</urlset>",
].join("\n");
writeFileSync(`${OUT_DIR}/sitemap.xml`, xml);

// sitemap-ai.xml — AI-priority subset (per bot-harvest.md Lever 5)
//   - all /source/<slug>/ pages with their JSON twin as alternate
//   - sub-tool ranking pages, methodology, sources index
const aiPriorityPaths = ["/", "/methodology/", "/sources/", "/discipline/", "/modern-reference/", "/velocity/"];
const aiHumanUrls = urls.filter((u) => aiPriorityPaths.some((p) => u.endsWith(p)) || u.includes("/source/"));

// Discover JSON twin endpoints generated by generate-api-json.ts
const apiSourceDir = join(OUT_DIR, "api", "source");
let apiUrls = [];
try {
  apiUrls = readdirSync(apiSourceDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => `${SITE}/api/source/${f}`);
} catch {
  // /api/ directory may not exist yet on first build; non-fatal.
}

const aiXml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap-0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ...aiHumanUrls.map((u) => {
    const slugMatch = u.match(/\/source\/([^/]+)\//);
    const altApi = slugMatch ? `${SITE}/api/source/${slugMatch[1]}.json` : null;
    const altLine = altApi
      ? `\n    <xhtml:link rel="alternate" type="application/json" href="${altApi}"/>`
      : "";
    return `  <url><loc>${u}</loc><lastmod>${TODAY}</lastmod><changefreq>weekly</changefreq><priority>1.0</priority>${altLine}</url>`;
  }),
  ...apiUrls.map(
    (u) =>
      `  <url><loc>${u}</loc><lastmod>${TODAY}</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>`
  ),
  "</urlset>",
].join("\n");
writeFileSync(`${OUT_DIR}/sitemap-ai.xml`, aiXml);

console.log(
  `✓ sitemap.xml (${urls.length} URLs) + sitemap-ai.xml (${aiHumanUrls.length} HTML + ${apiUrls.length} JSON)`
);
